name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["R-CMD-check"]
    types: [completed]
  workflow_dispatch:

jobs:
  pkgcheck:
    runs-on: ubuntu-26.04
    steps:
      - uses: ropensci-review-tools/pkgcheck-action@main
        with:
          summary-only: false
